version: '3'

services:

  nginx:
    image: "nginx"
    ports:
      -   8000:80
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/symfony-app/code/:/var/www/
    depends_on:
      - php

  php:
    image: bitnami/php-fpm
    volumes:
      - $HOME/symfony-app/code/:/var/www/

  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
